const deck=window.TAROT_DECK||[];const majorImageNames=window.TAROT_META?.majorImageNames||{"愚者":"ar00","魔术师":"ar01","女祭司":"ar02","皇后":"ar03","皇帝":"ar04","教皇":"ar05","恋人":"ar06","战车":"ar07","力量":"ar08","隐者":"ar09","命运之轮":"ar10","正义":"ar11","吊人":"ar12","死神":"ar13","节制":"ar14","恶魔":"ar15","高塔":"ar16","星星":"ar17","月亮":"ar18","太阳":"ar19","审判":"ar20","世界":"ar21"};
const suitImageCodes=window.TAROT_META?.suitImageCodes||{"权杖":"wa","圣杯":"cu","宝剑":"sw","星币":"pe"};
deck.forEach(d=>{let code=majorImageNames[d[0]];if(!code){let suit=Object.keys(suitImageCodes).find(x=>d[0].endsWith(x));let rank=d[0].slice(0,-suit.length);let ranks={"王牌":"01","二":"02","三":"03","四":"04","五":"05","六":"06","七":"07","八":"08","九":"09","十":"10","侍者":"11","骑士":"12","王后":"13","国王":"14"};code=suit?suitImageCodes[suit]+ranks[rank]:""}d[5]=code?"cards-webp/"+code+".webp":""});
let spread=1,selected=[],flipped=[],deckMode="full";const table=document.querySelector("#table"),reading=document.querySelector("#reading");document.querySelector(".intro p").insertAdjacentHTML("afterend",'<input id="question" class="question" maxlength="80" placeholder="写下你此刻想探索的问题（可选）"><select id="deck-mode" class="deck-mode"><option value="full">完整牌组 · 78 张</option><option value="major">大阿卡那 · 22 张</option></select>');document.querySelector("#deck-mode").onchange=e=>deckMode=e.target.value;
function render(){table.innerHTML="";const labels=spread===1?["今日指引"]:["过去","现在","未来"];for(let i=0;i<spread;i++){let slot=document.createElement("div");slot.className="card-slot"+(i>0?" locked":"");slot.innerHTML='<div class="slot-label">'+labels[i]+'</div>';let c=document.createElement("div");c.className="card back"+(!selected.length?" sealed":"");c.setAttribute("role","button");c.setAttribute("aria-disabled",!selected.length?"true":"false");c.setAttribute("tabindex",!selected.length?"-1":(i===0?"0":"-1"));c.setAttribute("aria-label","翻开"+labels[i]+"牌");c.onclick=()=>flip(i);c.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();flip(i)}};slot.append(c);table.append(slot)}}
function cardImage(d){return d[5]||""}function cardGuidance(d){return window.TAROT_GUIDANCE?.[d[0]]||{keywords:"觉察 · 选择",meaning:d[1],advice:"先确认眼前最重要的事实，再采取一个可执行的小步骤。",reversed:"放慢节奏，检查阻力和未被考虑的条件后再行动。"}}function cardKeywords(d){return cardGuidance(d).keywords}function cardAdvice(d){const guidance=cardGuidance(d);return d[4]?guidance.reversed:guidance.advice}
function flip(i){if(!selected.length)return;let slot=table.children[i],c=slot.querySelector(".card"),d=selected[i];if(slot.classList.contains("locked")||c.classList.contains("face")||c.classList.contains("flipping"))return;c.classList.add("flipping");setTimeout(()=>{c.className="card face"+(d[4]?" reversed":"");c.setAttribute("aria-disabled","false");let image=cardImage(d);c.innerHTML=(image?'<img src="'+escapeHTML(image)+'" alt="'+escapeHTML(d[0])+'" loading="lazy">':'<div class="sigil">'+escapeHTML(d[3])+'</div>')+'<b>'+escapeHTML(d[0])+'</b><small>'+(d[4]?"逆位":"正位")+"</small>";if(table.children[i+1]){table.children[i+1].classList.remove("locked");table.children[i+1].querySelector(".card").setAttribute("tabindex","0");document.querySelector(".hint").textContent="请翻开下一张牌"}flipped[i]=true;if(flipped.filter(Boolean).length===spread){document.querySelector(".hint").textContent="牌阵已完成 · 可以重新抽牌";let q=document.querySelector("#question").value.trim();reading.innerHTML="<h2>牌面讯息</h2>"+(q?'<p class="question-display">占问：'+escapeHTML(q)+'</p>':"")+selected.map((d,i)=>'<p><span class="position">'+(spread===1?"今日指引":["过去","现在","未来"][i])+" · "+escapeHTML(d[0])+" · "+(d[4]?"逆位":"正位")+"</span><br><strong>关键词：</strong>"+escapeHTML(cardKeywords(d))+"<br>"+escapeHTML(d[1])+"<br><strong>行动提示：</strong>"+escapeHTML(cardAdvice(d))+"</p>").join("");reading.classList.add("show");saveReading()}},720)}
document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("active"));b.classList.add("active");spread=+b.dataset.spread;selected=[];flipped=[];reading.classList.remove("show");render()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelector(".history-panel")?.remove()});new MutationObserver(()=>{let actions=document.querySelector(".history-actions");if(actions&&!actions.querySelector("#export-history")){let b=document.createElement("button");b.id="export-history";b.textContent="导出记录";actions.prepend(b);b.onclick=()=>{let blob=new Blob([JSON.stringify(getHistory(),null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="starry-tarot-history.json";a.click();URL.revokeObjectURL(url)}}}).observe(document.body,{childList:true,subtree:true});
document.addEventListener("pointerdown",e=>{if(e.target.closest(".draw button,.choice"))sparkle(e.clientX,e.clientY)});document.querySelector("#draw").onclick=()=>{let button=document.querySelector("#draw");button.disabled=true;button.textContent="星尘洗牌中…";selected=[];flipped=[];reading.classList.remove("show");render();document.querySelectorAll(".card").forEach(c=>c.classList.add("shuffling"));setTimeout(()=>{let pool=(deckMode==="major"?deck.slice(0,22):deck).slice();selected=Array.from({length:spread},()=>{let d=pool.splice(Math.floor(Math.random()*pool.length),1)[0].slice();d[4]=Math.random()<.28;return d});button.disabled=false;button.textContent="开始抽牌";document.querySelector(".hint").textContent="请翻开第一张牌";render();document.querySelectorAll(".card").forEach(c=>{c.classList.add("unsealing");setTimeout(()=>c.classList.remove("unsealing"),820)})},850)};document.querySelector("#history").onclick=showHistory;document.querySelector("#count").textContent=getHistory().length;render();
 document.addEventListener("animationstart",e=>{if(e.animationName==="cardFlipPro")e.target.classList.add("revealed")});
document.addEventListener("error",e=>{if(e.target.tagName==="IMG"){e.target.style.display="none"}},true);
document.addEventListener("animationstart",e=>{if(e.animationName==="cardFlipPro"){let r=e.target.getBoundingClientRect();sparkle(r.left+r.width/2,r.top+r.height/2)}});

document.querySelectorAll(".choice").forEach(b=>b.setAttribute("aria-pressed",b.classList.contains("active")?"true":"false"));document.addEventListener("click",e=>{let b=e.target.closest(".choice");if(b)document.querySelectorAll(".choice").forEach(x=>x.setAttribute("aria-pressed",x===b?"true":"false"))});
const openHistory=showHistory;document.querySelector("#history").onclick=()=>{document.querySelector(".history-panel")?.remove();openHistory()};
document.addEventListener("click",e=>{if(e.target.classList.contains("history-panel"))e.target.remove()});
reading.setAttribute("aria-live","polite");reading.setAttribute("aria-atomic","true");new MutationObserver(()=>{document.body.style.overflow=document.querySelector(".history-panel")?"hidden":""}).observe(document.body,{childList:true});


document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelector(".card-detail .detail-close")?.click()});
function openCardDetail(card){if(document.querySelector(".card-detail"))return;let overlay=document.createElement("div");overlay.className="card-detail";overlay.setAttribute("role","dialog");overlay.setAttribute("aria-modal","true");let panel=document.createElement("div");panel.className="card-detail-panel";let clone=card.cloneNode(true);clone.classList.remove("enlarged");clone.classList.add("detail-card");clone.removeAttribute("aria-disabled");clone.setAttribute("tabindex","-1");clone.querySelector("img")?.setAttribute("decoding","async");let name=card.querySelector("b")?.textContent||"牌面",data=selected.find(d=>d[0]===name),guidance=data?cardGuidance(data):{keywords:"觉察 · 选择",meaning:"留意这张牌在当前问题中的提示。",advice:"先确认眼前最重要的事实，再采取一个可执行的小步骤。",reversed:"放慢节奏，检查阻力和未被考虑的条件后再行动。"};let title=document.createElement("h2");title.textContent=name;let status=document.createElement("p");status.className="detail-status";status.textContent=card.querySelector("small")?.textContent||"";let keywords=document.createElement("p");keywords.className="detail-keywords";keywords.textContent="关键词："+guidance.keywords;let meaning=document.createElement("p");meaning.className="detail-meaning";meaning.textContent=guidance.meaning;let advice=document.createElement("p");advice.className="detail-advice";advice.textContent="行动建议："+(data?cardAdvice(data):guidance.advice);let close=document.createElement("button");close.className="detail-close";close.type="button";close.textContent="关闭";panel.append(clone,title,status,keywords,meaning,advice,close);overlay.append(panel);document.body.append(overlay);document.body.style.overflow="hidden";close.focus();const closeDetail=()=>{overlay.remove();document.body.style.overflow="";card.focus()};close.onclick=closeDetail;overlay.onclick=e=>{if(e.target===overlay)closeDetail()};overlay.addEventListener("keydown",e=>{if(e.key==="Escape"){e.preventDefault();closeDetail()}})}
document.addEventListener("click",e=>{let card=e.target.closest(".card.face");if(card&&!e.target.closest(".card-detail"))openCardDetail(card)});
sparkle=function(x,y){for(let i=0;i<4;i++){let s=document.createElement("span"),angle=(Math.PI*2*i/4)+Math.random()*.35,distance=18+Math.random()*20,dx=Math.cos(angle)*distance,dy=Math.sin(angle)*distance;s.className="star-particle";s.style.left=x-3+"px";s.style.top=y-3+"px";s.style.willChange="transform,opacity";document.body.append(s);if(s.animate){s.animate([{opacity:0,transform:"translate(0,0) scale(.2)"},{opacity:1,transform:"translate("+(dx*.25)+"px,"+(dy*.25)+"px) scale(1)"},{opacity:0,transform:"translate("+dx+"px,"+dy+"px) scale(1.5)"}],{duration:720,delay:i*55,easing:"cubic-bezier(.2,.8,.3,1)",fill:"both"})}else{s.style.setProperty("--dx",dx+"px");s.style.setProperty("--dy",dy+"px");s.style.animation="starParticle .72s ease-out "+i*.055+"s both"}setTimeout(()=>s.remove(),950)}};
document.addEventListener("keydown",e=>{const dialog=document.querySelector(".card-detail");if(!dialog||e.key!=="Tab")return;const focusables=[...dialog.querySelectorAll("button,[tabindex]:not([tabindex='-1'])")];if(!focusables.length)return;const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});new MutationObserver(()=>{if(reading.classList.contains("show"))reading.scrollIntoView({behavior:"smooth",block:"start"});document.querySelectorAll(".face img").forEach(img=>img.decoding="async")}).observe(reading,{attributes:true,attributeFilter:["class"]});











